"""database creation

Revision ID: a1cc99319676
Revises: 
Create Date: 2023-03-27 16:09:28.029725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1cc99319676'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('superlatives',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('date_expired', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP + 10000)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voter', sa.Integer(), nullable=True),
    sa.Column('superlative', sa.Integer(), nullable=True),
    sa.Column('candidate', sa.Integer(), nullable=True),
    sa.Column('date_voted', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['candidate'], ['users.id'], ),
    sa.ForeignKeyConstraint(['superlative'], ['superlatives.id'], ),
    sa.ForeignKeyConstraint(['voter'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    op.drop_table('superlatives')
    op.drop_table('users')
    # ### end Alembic commands ###
