"""changed date_expired column

Revision ID: d14281006ad8
Revises: 20cd6e523488
Create Date: 2023-03-28 16:29:51.929347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd14281006ad8'
down_revision = '20cd6e523488'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
