"""changed date_expired update

Revision ID: f639bf7c4b83
Revises: d14281006ad8
Create Date: 2023-03-28 16:36:02.566793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f639bf7c4b83'
down_revision = 'd14281006ad8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
