"""changed date_expired update

Revision ID: fb625685c8d4
Revises: f639bf7c4b83
Create Date: 2023-03-28 16:51:15.596580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb625685c8d4'
down_revision = 'f639bf7c4b83'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
